In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./train.csv")
testdf = pd.read_csv("./testdata.csv",header=None)

In [3]:
df.head(19) #总共18个数值

Date stations observation     0     1     2     3     4     5     6  \
0   2014/1/1  station    AMB_TEMP    13    14    14    13    12    12    12   
1   2014/1/1  station         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2   2014/1/1  station          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3   2014/1/1  station        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4   2014/1/1  station          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
5   2014/1/1  station         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   
6   2014/1/1  station         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   
7   2014/1/1  station          O3    16    30    27    23    24    28    24   
8   2014/1/1  station        PM10    56    50    48    35    25    12     4   
9   2014/1/1  station       PM2.5    26    39    36    35    31    28    25   
10  2014/1/1  station    RAINFALL    NR    NR    NR    NR    NR    NR    NR   
11  2014/1/1  station          RH    77    68    67    74    72    73    74   
12  2014/1/1  station         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5   
13  2014/1/1  station         THC     2     2     2   1.9   1.9   1.8   1.9   
14  2014/1/1  station       WD_HR    37    80    57    76   110   106   101   
15  2014/1/1  station  WIND_DIREC    35    79   2.4    55    94   116   106   
16  2014/1/1  station  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5   
17  2014/1/1  station       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2   
18  2014/1/2  station    AMB_TEMP    16    15    15    14    14    15    16   

    ...    14    15    16    17    18    19    20    21    22    23  
0   ...    22    22    21    19    17    16    15    15    15    15  
1   ...   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2   ...  0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3   ...   0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4   ...   2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5   ...    11    11    22    28    19    12   8.1     7   6.9     6  
6   ...    14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7   ...    65    64    51    34    33    34    37    38    38    36  
8   ...    52    51    66    85    85    63    46    36    42    42  
9   ...    36    45    42    49    45    44    41    30    24    13  
10  ...    NR    NR    NR    NR    NR    NR    NR    NR    NR    NR  
11  ...    47    49    56    67    72    69    70    70    70    69  
12  ...   3.9   4.4   9.9   5.1   3.4   2.3     2   1.9   1.9   1.9  
13  ...   1.9   1.9   1.9   2.1     2   1.9   1.9   1.9   1.9   1.9  
14  ...   307   304   307   124   118   121   113   112   106   110  
15  ...   313   305   291   124   119   118   114   108   102   111  
16  ...   2.5   2.2   1.4   2.2   2.8     3   2.6   2.7   2.1   2.1  
17  ...   2.1   2.1   1.9     1   2.5   2.5   2.8   2.6   2.4   2.3  
18  ...    24    24    23    21    20    19    18    18    18    18  

[19 rows x 27 columns]

In [4]:
data = df[df['observation']=='PM2.5']
data = data.iloc[:,3:].to_numpy(dtype='float').flatten()
data

array([26., 39., 36., ..., 17., 24., 29.])

In [5]:
x = []
y = []
for i in range(len(data)-9):
    x.append(list(data[i:i+9]))
y = data[9:]
x = np.array(x)

In [6]:
testdata = testdf[testdf[1]=='PM2.5']
testx = testdata.iloc[:,2:].to_numpy(dtype='float')
testx

array([[26., 13., 24., ..., 29., 27., 28.],
       [46., 47., 57., ..., 59., 61., 61.],
       [10., 10., 25., ..., 36., 25., 22.],
       ...,
       [16., 25., 12., ..., 11.,  3.,  0.],
       [29., 27., 23., ..., 35., 35., 26.],
       [12.,  8.,  7., ...,  0.,  0.,  0.]])

# least square method

In [7]:
w = np.matmul(np.matmul(np.linalg.pinv(np.matmul(x.transpose(),x)),x.transpose()),y)
w

array([-7.58275411e-03, -2.61478584e-02,  2.04859536e-01, -2.13171762e-01,
       -5.72546428e-02,  5.19080271e-01, -5.53909496e-01, -2.06645086e-05,
        1.10967794e+00])

优化算法可调整的地方
+ Batch
+ 学习率
+ 自适应  ada
+ 梯度估计

sgd和mini-sgd就是智障儿童

# BGD

In [8]:
 def bgd(x,y,epochs=10000):
    """
    bgd
    """
    w = np.zeros(len(x[0]))
    l_rate = 0.0001    # 学习率
    
    for i in range(epochs):
        error = np.dot(x,w)-y
        loss = np.dot(error.T,error)/len(x)/2
        grad = np.dot(x.T,error)/len(x)
        w = w - l_rate * grad
        if i%100==0:
            print ('epoch: %d ======>> Loss: %f ' % (i,loss))
    
    return w

In [9]:
w = bgd(x,y)

epoch: 0 ======>> Loss: 367.974352 
epoch: 100 ======>> Loss: 28.851832 
epoch: 200 ======>> Loss: 24.795856 
epoch: 300 ======>> Loss: 23.129168 
epoch: 400 ======>> Loss: 22.212393 
epoch: 500 ======>> Loss: 21.632790 
epoch: 600 ======>> Loss: 21.233816 
epoch: 700 ======>> Loss: 20.943035 
epoch: 800 ======>> Loss: 20.722412 
epoch: 900 ======>> Loss: 20.550088 
epoch: 1000 ======>> Loss: 20.412597 
epoch: 1100 ======>> Loss: 20.301169 
epoch: 1200 ======>> Loss: 20.209807 
epoch: 1300 ======>> Loss: 20.134240 
epoch: 1400 ======>> Loss: 20.071320 
epoch: 1500 ======>> Loss: 20.018657 
epoch: 1600 ======>> Loss: 19.974396 
epoch: 1700 ======>> Loss: 19.937071 
epoch: 1800 ======>> Loss: 19.905510 
epoch: 1900 ======>> Loss: 19.878760 
epoch: 2000 ======>> Loss: 19.856044 
epoch: 2100 ======>> Loss: 19.836720 
epoch: 2200 ======>> Loss: 19.820260 
epoch: 2300 ======>> Loss: 19.806220 
epoch: 2400 ======>> Loss: 19.794232 
epoch: 2500 ======>> Loss: 19.783986 
epoch: 2600 ======>> Lo

In [10]:
w

array([-7.68943868e-03, -2.58562834e-02,  2.04589983e-01, -2.13218595e-01,
       -5.68827448e-02,  5.18732687e-01, -5.53883858e-01,  2.01733082e-04,
        1.10953497e+00])

# SGD

In [11]:
def sgd(x,y,epochs=10000):
    """
    sgd
    """
    w = np.zeros(len(x[0]))
    l_rate = 0.0001    # 学习率
    G = np.zeros(len(x[0]))
    
    for i in range(epochs):
        error = np.dot(x,w)-y
        loss = np.dot(error.T,error)/len(x)/2
        # random
        j = np.random.randint(0, len(x[0]))
        w = w - l_rate * (x[j] * (np.dot(x[j], w) - y[j]))
        if i%100==0:
            print ('epoch: %d ======>> Loss: %f ' % (i,loss))
    
    return w

In [12]:
w = sgd(x,y)

epoch: 0 ======>> Loss: 367.974352 
epoch: 100 ======>> Loss: 64.901270 
epoch: 200 ======>> Loss: 118.972488 
epoch: 300 ======>> Loss: 75.618000 
epoch: 400 ======>> Loss: 101.150133 
epoch: 500 ======>> Loss: 99.867365 
epoch: 600 ======>> Loss: 101.671934 
epoch: 700 ======>> Loss: 95.859858 
epoch: 800 ======>> Loss: 70.954428 
epoch: 900 ======>> Loss: 71.151333 
epoch: 1000 ======>> Loss: 79.671862 
epoch: 1100 ======>> Loss: 104.384197 
epoch: 1200 ======>> Loss: 95.751564 
epoch: 1300 ======>> Loss: 64.156193 
epoch: 1400 ======>> Loss: 79.556975 
epoch: 1500 ======>> Loss: 104.874179 
epoch: 1600 ======>> Loss: 98.210079 
epoch: 1700 ======>> Loss: 75.258267 
epoch: 1800 ======>> Loss: 93.673738 
epoch: 1900 ======>> Loss: 86.058415 
epoch: 2000 ======>> Loss: 86.771058 
epoch: 2100 ======>> Loss: 76.360263 
epoch: 2200 ======>> Loss: 97.755575 
epoch: 2300 ======>> Loss: 94.001246 
epoch: 2400 ======>> Loss: 99.657312 
epoch: 2500 ======>> Loss: 87.070669 
epoch: 2600 ======

In [13]:
w

array([ 0.41608997, -0.52791796,  0.72268376, -0.0827027 , -0.10076389,
        0.91490412, -0.67533647,  0.2535061 ,  0.32665776])

# Mini-batch-gd

In [14]:
def mini(x,y,epochs=100000):
    """
    mini
    """
    w = np.zeros(len(x[0]))
    l_rate = 0.00001    # 学习率
    G = np.zeros(len(x[0]))
    
    for i in range(epochs):
        error = np.dot(x,w)-y
        loss = np.dot(error.T,error)/len(x)/2
        # 一个个batch算
        j = i%len(x)
        w = w - l_rate * (x[j] * (np.dot(x[j], w) - y[j]))
        if i%1000==0:
            print ('epoch: %d ======>> Loss: %f ' % (i,loss))
    
    return w

In [15]:
w = mini(x,y)

epoch: 0 ======>> Loss: 367.974352 
epoch: 1000 ======>> Loss: 42.101758 
epoch: 2000 ======>> Loss: 26.489624 
epoch: 3000 ======>> Loss: 28.832176 
epoch: 4000 ======>> Loss: 23.987071 
epoch: 5000 ======>> Loss: 39.160613 
epoch: 6000 ======>> Loss: 22.234630 
epoch: 7000 ======>> Loss: 38.408013 
epoch: 8000 ======>> Loss: 22.984721 
epoch: 9000 ======>> Loss: 22.048664 
epoch: 10000 ======>> Loss: 21.342991 
epoch: 11000 ======>> Loss: 24.232250 
epoch: 12000 ======>> Loss: 21.352925 
epoch: 13000 ======>> Loss: 21.903494 
epoch: 14000 ======>> Loss: 21.005412 
epoch: 15000 ======>> Loss: 21.077765 
epoch: 16000 ======>> Loss: 20.720242 
epoch: 17000 ======>> Loss: 20.906021 
epoch: 18000 ======>> Loss: 21.545032 
epoch: 19000 ======>> Loss: 20.439513 
epoch: 20000 ======>> Loss: 20.807528 
epoch: 21000 ======>> Loss: 20.719552 
epoch: 22000 ======>> Loss: 20.365286 
epoch: 23000 ======>> Loss: 20.203713 
epoch: 24000 ======>> Loss: 24.994345 
epoch: 25000 ======>> Loss: 20.940072

In [16]:
w

array([ 0.01631788, -0.02818291,  0.17306605, -0.18196815, -0.03098606,
        0.46187467, -0.53455503, -0.00357345,  1.02746172])

# Adagrad

In [31]:
def adagrad(x,y,epochs=10000):
    """
    adagrad
    """
    w = np.zeros(len(x[0]))
    l_rate = 100    # 学习率
    G = np.zeros(len(x[0]))
    
    for i in range(epochs):
        error = np.dot(x,w)-y
        loss = np.dot(error.T,error)/len(x)/2
        grad = np.dot(x.T,error)/len(x)
        G += grad**2
        ada = np.sqrt(G+1e-8)
        w = w - l_rate * grad/ada
        if i%100==0:
            print ('epoch: %d ======>> Loss: %f ' % (i,loss))
    
    return w

In [32]:
w = adagrad(x,y)

epoch: 0 ======>> Loss: 367.974352 
epoch: 100 ======>> Loss: 25.667039 
epoch: 200 ======>> Loss: 22.741831 
epoch: 300 ======>> Loss: 21.619753 
epoch: 400 ======>> Loss: 21.026114 
epoch: 500 ======>> Loss: 20.660285 
epoch: 600 ======>> Loss: 20.414796 
epoch: 700 ======>> Loss: 20.241594 
epoch: 800 ======>> Loss: 20.115636 
epoch: 900 ======>> Loss: 20.022278 
epoch: 1000 ======>> Loss: 19.952208 
epoch: 1100 ======>> Loss: 19.899154 
epoch: 1200 ======>> Loss: 19.858726 
epoch: 1300 ======>> Loss: 19.827771 
epoch: 1400 ======>> Loss: 19.803980 
epoch: 1500 ======>> Loss: 19.785642 
epoch: 1600 ======>> Loss: 19.771472 
epoch: 1700 ======>> Loss: 19.760504 
epoch: 1800 ======>> Loss: 19.751999 
epoch: 1900 ======>> Loss: 19.745396 
epoch: 2000 ======>> Loss: 19.740263 
epoch: 2100 ======>> Loss: 19.736270 
epoch: 2200 ======>> Loss: 19.733159 
epoch: 2300 ======>> Loss: 19.730735 
epoch: 2400 ======>> Loss: 19.728844 
epoch: 2500 ======>> Loss: 19.727368 
epoch: 2600 ======>> Lo

In [19]:
w

array([-7.58463425e-03, -2.61435990e-02,  2.04856821e-01, -2.13174124e-01,
       -5.72486933e-02,  5.19076318e-01, -5.53910651e-01, -1.67727043e-05,
        1.10967587e+00])

# RMSprop

In [35]:
def RMSprop(x,y,epochs=10000):
    """
    RMSprop
    """
    w = np.zeros(len(x[0]))
    l_rate = 0.001   # 学习率
    beta = 0.9    # 指数平均权重
    G = np.zeros(len(x[0]))
    
    for i in range(epochs):
        error = np.dot(x,w)-y
        loss = np.dot(error.T,error)/len(x)/2
        grad = np.dot(x.T,error)/len(x)
        G = beta*G + (1-beta)*grad**2
        ada = np.sqrt(G+1e-8)
        w = w - l_rate * grad/ada
        if i%100==0:
            print ('epoch: %d ======>> Loss: %f ' % (i,loss))
    
    return w

In [36]:
w = RMSprop(x,y)

epoch: 0 ======>> Loss: 367.974352 
epoch: 100 ======>> Loss: 72.114315 
epoch: 200 ======>> Loss: 51.308247 
epoch: 300 ======>> Loss: 41.189774 
epoch: 400 ======>> Loss: 34.427391 
epoch: 500 ======>> Loss: 30.148275 
epoch: 600 ======>> Loss: 27.093621 
epoch: 700 ======>> Loss: 24.667122 
epoch: 800 ======>> Loss: 22.814009 
epoch: 900 ======>> Loss: 21.504573 
epoch: 1000 ======>> Loss: 20.693840 
epoch: 1100 ======>> Loss: 20.271253 
epoch: 1200 ======>> Loss: 20.051926 
epoch: 1300 ======>> Loss: 19.927414 
epoch: 1400 ======>> Loss: 19.853240 
epoch: 1500 ======>> Loss: 19.807786 
epoch: 1600 ======>> Loss: 19.779399 
epoch: 1700 ======>> Loss: 19.761433 
epoch: 1800 ======>> Loss: 19.749955 
epoch: 1900 ======>> Loss: 19.742571 
epoch: 2000 ======>> Loss: 19.737795 
epoch: 2100 ======>> Loss: 19.734693 
epoch: 2200 ======>> Loss: 19.732670 
epoch: 2300 ======>> Loss: 19.731346 
epoch: 2400 ======>> Loss: 19.730478 
epoch: 2500 ======>> Loss: 19.729906 
epoch: 2600 ======>> Lo

In [22]:
w

array([-7.42063383e-03, -2.59822748e-02,  2.05027558e-01, -2.13002483e-01,
       -5.70848966e-02,  5.19249575e-01, -5.53741447e-01,  1.44918824e-04,
        1.10984004e+00])

# Adam

In [33]:
def Adam(x,y,epochs=10000):
    """
    Adam
    """
    w = np.zeros(len(x[0]))
    l_rate = 0.001   # 学习率
    beta1 = 0.9    
    beta2 = 0.99
    G = np.zeros(len(x[0]))
    Mom = np.zeros(len(x[0]))
    
    for i in range(epochs):
        error = np.dot(x,w)-y
        loss = np.dot(error.T,error)/len(x)/2
        grad = np.dot(x.T,error)/len(x)
        
        Mom = beta1*Mom + (1-beta1)*grad
        Mom_ = Mom/(1-beta1**(i+1))
        
        G = beta2*G + (1-beta2)*grad**2
        G_ = G / (1-beta2**(i+1))
        ada = np.sqrt(G_+1e-8)
        
        w = w - l_rate * Mom_/ada
        if i%100==0:
            print ('epoch: %d ======>> Loss: %f ' % (i,loss))
    
    return w

In [34]:
w = Adam(x,y)

epoch: 0 ======>> Loss: 367.974352 
epoch: 100 ======>> Loss: 84.875004 
epoch: 200 ======>> Loss: 63.361518 
epoch: 300 ======>> Loss: 55.634565 
epoch: 400 ======>> Loss: 47.805326 
epoch: 500 ======>> Loss: 41.329646 
epoch: 600 ======>> Loss: 36.470155 
epoch: 700 ======>> Loss: 32.688105 
epoch: 800 ======>> Loss: 29.671295 
epoch: 900 ======>> Loss: 27.267965 
epoch: 1000 ======>> Loss: 25.300636 
epoch: 1100 ======>> Loss: 23.633689 
epoch: 1200 ======>> Loss: 22.245050 
epoch: 1300 ======>> Loss: 21.171366 
epoch: 1400 ======>> Loss: 20.429225 
epoch: 1500 ======>> Loss: 19.991038 
epoch: 1600 ======>> Loss: 19.789522 
epoch: 1700 ======>> Loss: 19.729914 
epoch: 1800 ======>> Loss: 19.722285 
epoch: 1900 ======>> Loss: 19.722033 
epoch: 2000 ======>> Loss: 19.722034 
epoch: 2100 ======>> Loss: 19.722057 
epoch: 2200 ======>> Loss: 19.722047 
epoch: 2300 ======>> Loss: 19.722045 
epoch: 2400 ======>> Loss: 19.722117 
epoch: 2500 ======>> Loss: 19.722037 
epoch: 2600 ======>> Lo

In [25]:
w

array([-7.61567323e-03, -2.61814800e-02,  2.04825418e-01, -2.13206135e-01,
       -5.72891094e-02,  5.19045894e-01, -5.53943619e-01, -5.42861041e-05,
        1.10964503e+00])

# 测试数据

In [26]:
test_y=np.dot(testx,w)
test_y[test_y<0]=0

In [27]:
ans = pd.read_csv('ans.csv')
rmse = np.sqrt(np.linalg.norm((ans.iloc[:,1]-test_y),2)**2/240)
rmse

6.664919818442531

In [28]:
sample = pd.read_csv('sampleSubmission.csv')
sample['value']=test_y
sample.to_csv('sampleSubmission1.csv',index=0)
pd.read_csv('sampleSubmission1.csv')

id      value
0      id_0  26.421219
1      id_1  63.101684
2      id_2  19.953744
3      id_3  29.530948
4      id_4   9.276387
..      ...        ...
235  id_235  21.082764
236  id_236  11.473793
237  id_237   0.000000
238  id_238  21.378107
239  id_239   0.000000

[240 rows x 2 columns]